hash-format = "sha256"

[[files]]
file = "mods/AdvancedPeripherals.jar"
hash = "55a51ab7657e5d43a00f998f36142c06776b27226924cb893ce0d628929d048c"

[[files]]
file = "mods/ChatIA.jar"
hash = "b3ec7839deeb9db9e4eafc8e501ae33b39ff1d2f1054e6eadaf8c6525e12388a"

[[files]]
file = "mods/Clumps.jar"
hash = "b524ccdace2ef8fd19f5b2074f7de1103ac5065c52553f064c00e098346c293e"

[[files]]
file = "mods/CreaterLib.jar"
hash = "189255780fd95d5e415167f09247c13a7cda0f74c7f93756b19a5c288dc6fe06"

[[files]]
file = "mods/IF.jar"
hash = "1998d56edb0ddb6caeedd09dd2fde405ee85cd8f706398cb8e08009fe9019058"

[[files]]
file = "mods/Jade.jar"
hash = "7087a9672a208071e774571423793d499a56adc8dd09fabe36f8652a3bb9c418"

[[files]]
file = "mods/Mekanism.jar"
hash = "0be01fe153c17a8aab4c923e44f5e7546d69b37007b757580c85af7ec846cc5a"

[[files]]
file = "mods/MouseTweaks.jar"
hash = "68e6f4201c5de97b77929a7215c9552495696ca6a3bf3ae4eacc34e135f6cc8b"

[[files]]
file = "mods/XaerosM.jar"
hash = "35d5217f497d7747a78670b0280b28dc22630a244ffd93a09c4cf8789b9353ba"

[[files]]
file = "mods/XaerosWM.jar"
hash = "39285c3533f8b83f22cb2454cb05a5350041d08581677f6ed1e21cbaf6c92d81"

[[files]]
file = "mods/YAC.jar"
hash = "eee4ed85a32a8f6b04c3c85daf5e91bc83ba95d391976af41d8f85491643d0dd"

[[files]]
file = "mods/[1.21.1] SecurityCraft.jar"
hash = "ed98e1ad30360ec36d58962ce9d3891e2e6c1a3c68ed07f9545040b9ced85ede"

[[files]]
file = "mods/admin_panel.jar"
hash = "b372a4ad1306e836b99398e63b65f09909b7ce3e81eb6a39f8c5dc3ce76dc96a"

[[files]]
file = "mods/aeinfinitybooster.jar"
hash = "21635ecbf2f5fa7bdcbab6e945e9e720fc7de4599b4257fe7e9e855c4488f95a"

[[files]]
file = "mods/amendments.jar"
hash = "33f5b4f2667475919ddd79c6428d207a21f1f2ca23868dd963571d196d275015"

[[files]]
file = "mods/appliedenergistics.jar"
hash = "460d779a0609b81409907d9956de8f6f70a1b0912257e3e5c3c7e75ac9630e95"

[[files]]
file = "mods/architectury.jar"
hash = "5ec578f814e8cca87aeffa6e424032e78d9ea5ea6b603dd834c2dc13c31141ee"

[[files]]
file = "mods/bookshelf.jar"
hash = "9d868be040c2ba6e2f31c40278b73d8ff383e1f8d7005a6f9820c0d1c4cf61b5"

[[files]]
file = "mods/caelus.jar"
hash = "432a645557f29de159d9edde2fd109f8e3b32ff30895b4fede04ee5f1a1a682f"

[[files]]
file = "mods/cccbridge.jar"
hash = "cc268961ea1b1a0d4e36eaff36d8b987e2f65b113d230a125953778ec83c6687"

[[files]]
file = "mods/cctweaked.jar"
hash = "f5e8872a2ccca38aa210c477c84d5f2ba3e8f054328b6816461af4c1f8c460a5"

[[files]]
file = "mods/chat_heads.jar"
hash = "246a92b608cac6b354caa21f85b8983eaba2dfa76cdedde17185e6d569cee457"

[[files]]
file = "mods/chatplus.jar"
hash = "63cb987a64a58af88626573198181c4d7714d147a0c9e70c445f394984fdab6a"

[[files]]
file = "mods/chunky.jar"
hash = "d72f235cf1f56f2c374f52c00bdda5034524b28142305a84cfc123a3f92ad274"

[[files]]
file = "mods/cloth.jar"
hash = "65e722e0d98431a07c45f8bdd8d529a217cc8c175fde1740248bd5c1b4f3c0d4"

[[files]]
file = "mods/copycats.jar"
hash = "8caf0e53cf250e1cc2811d49e9ea46f3c691f65c3522b55c19e24a411d1354ef"

[[files]]
file = "mods/create.jar"
hash = "2d403500cd550db452a975ec3d4ba21b6097360d4dd575311112fe322055b1ee"

[[files]]
file = "mods/createA.jar"
hash = "91b020cd72a9d7ab7091947f693d1aacbc493bd35f514fa31737021c3548fe34"

[[files]]
file = "mods/createCCL.jar"
hash = "bdb11c6862f6c7c3311bb5d605264119231c7c8ce5789e8dfd54e769f04a170f"

[[files]]
file = "mods/createDP.jar"
hash = "213fa28efdc530ba87d6a5e5be7876b4cf3a3994624c5a266661d43889088f34"

[[files]]
file = "mods/createEI.jar"
hash = "1cc20ff42f2fb8132d9978ba7a26d888088965e43a98c44489efd5ffd5a617d9"

[[files]]
file = "mods/createEM.jar"
hash = "05e73d71f2fcce12560e329b51197a5caaf705847748f5bfdfcad6753b281473"

[[files]]
file = "mods/createF.jar"
hash = "50269db454494535258c1b44af201a5e69c44a0c04907a4c071f06f80bd87424"

[[files]]
file = "mods/createPW.jar"
hash = "31004286d41510b07e812912f8510696065f77be593098a163701d26d4ffe17d"

[[files]]
file = "mods/createSB.jar"
hash = "505d4f65b8692d3fb66684f7389fd8b80f4710194f0ea8822e942888c8ab9e52"

[[files]]
file = "mods/createUF.jar"
hash = "75f00a6f049176b26cb281613d8d93ad2c69bb8072c937b59cc777b8b2585f6c"

[[files]]
file = "mods/curios.jar"
hash = "a45df2125c26219974aba7507ffc9afe7b83acc941a386af3faacb1cc0056fde"

[[files]]
file = "mods/elytraslot.jar"
hash = "d86adf384390c40b144a296ef4fc11b72fd81e2780b264bd9ceb7b5ab9147399"

[[files]]
file = "mods/enchdesc.jar"
hash = "74d546ecb147da7e2cb53fe3115f6e062094329dcf15639b3da694cc00d3f843"

[[files]]
file = "mods/entityculling.jar"
hash = "c30406bd4b5aa7416f0889b69ffcd6cd4defed6ef2055254f8b5a9d1ae9ca223"

[[files]]
file = "mods/essential.jar"
hash = "07418e43aa2339a11cd81915e44e0b037cd60db124b0ba5cb96c7afd469208b7"

[[files]]
file = "mods/ferritecore.jar"
hash = "235e2081dfe050d7642b0d432a786668f079168505ba5d6bf0ec70c962a36539"

[[files]]
file = "mods/freecam.jar"
hash = "09b865a3987a0f1c87bcc9430550ccc4107729f29bff53a1cd5ab1e9c3d82376"

[[files]]
file = "mods/guideme.jar"
hash = "8c6729b1097ba142cfde9410403244d8179d92ce8c4c0d086a448bc0fc093f55"

[[files]]
file = "mods/index.toml"
hash = "8001c399d72f24890a88ed2d4cee6896c93739485010e1213d40e51c9838864a"

[[files]]
file = "mods/iz.jar"
hash = "dd01bba1f105d9386d827c940844b704cbf63fdb1ecf09605b9bfd4b5b18298b"

[[files]]
file = "mods/jei.jar"
hash = "360d627c4c81f9eb42e0d1f316bac66765596405790809cf64655bdefc0b0307"

[[files]]
file = "mods/kotlinff.jar"
hash = "3f6e1d0e34c86e62abce3a9f86764a6861a2101aaa8858ada9d81f4588336efe"

[[files]]
file = "mods/loadsupport.jar"
hash = "1077cbbc9640f848ee3cf003ac640ae9fd56b89487093c6755c8298d40d9ae12"

[[files]]
file = "mods/mekG.jar"
hash = "4fc811d5787d8c9bf9c5d5d7bae4a86afcd6a304bb8d28509ee5626491e702e8"

[[files]]
file = "mods/mekc.jar"
hash = "7e67b8f5c111ef0d94abcd0c24580fa74c0532dbfa9e5cdbf58521e57cbbdc95"

[[files]]
file = "mods/modelfix.jar"
hash = "ee774b72135450ef9db1c7a75837304f30d05c3541e3a348c4f5769ab0f04912"

[[files]]
file = "mods/modernfix.jar"
hash = "0f1f987cdb9f1896217d45d91a9eaa20ee4c0054c41602624b54d81513a8cc22"

[[files]]
file = "mods/moonlight.jar"
hash = "b59edf72f4dd4ed97841e5f6ab4f7f64990ce410f7e43682a9397a3a8f72b89c"

[[files]]
file = "mods/neoCarpet.jar"
hash = "2dfbaf230036111f8055fadc8c908d6dec50088fb5d833390f5067aed5d04c36"

[[files]]
file = "mods/neoJCM.jar"
hash = "22c3c9069dd4fa33033b8419e259cf118ac5985925ff280daf19af70033ea2f4"

[[files]]
file = "mods/neoLU.jar"
hash = "fbdc1cac923e85c5d92c75dbfc81c7f5df27959fffed5df0642caabdac226767"

[[files]]
file = "mods/neoMSD.jar"
hash = "4e13e1e57bb2a990695a50c9a7ccd928bc5cba1c143ca152638ee15a36960a38"

[[files]]
file = "mods/neoMTR.jar"
hash = "9c6da1aaa7cb6fc5511ca330f44c69c5c3a79def93c0e588c8cbf91484a0c4d8"

[[files]]
file = "mods/prickle.jar"
hash = "ccf46c442ed3c7fe41ad056f0940560829ec4dd88360985dfacd78f4614eb167"

[[files]]
file = "mods/reforgedplaymod-1.21.1-0.3.jar"
hash = "608481672d6afbd0926427e58dcbfb1c66421d9364aa00e67696bcdc9c5f5cc0"

[[files]]
file = "mods/skinlayers3d.jar"
hash = "d6864ecc8e7a169fcecbcdbaab024ff3b364f093abbedb041afe8515ee5628b8"

[[files]]
file = "mods/slideshow.jar"
hash = "a445cc68987408e8ed5270de0e0d7de4040ea1a97bb2b36e2858e39f571b766c"

[[files]]
file = "mods/supplementaries.jar"
hash = "2200f725ffd1b2d1f3e772c2a32b344b0700ed6fe4d56285287d20c929c0157d"

[[files]]
file = "mods/trafficcraft.jar.jar"
hash = "21eb68e5ecec6a000c6e266c189b653d6e46b8a7f298bb0c68a54a87dfa0448b"

[[files]]
file = "mods/voicechat.jar"
hash = "d1a6a5653bb367013a4d9667803b9c35b8a68df6cd63ab1667a8c89a472b9165"

[[files]]
file = "mods/worldedit.jar"
hash = "5e7752c97876d87411e3760bcc573cc431f43c453722e6959fa7fe54db1b01ca"
