hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "2e5bcd5df77fd7f0dc6e35016e9d212fc7c9cdef4a6038e884dccdc7df7f73ff"
metafile = true

[[files]]
file = "mods/YAC.pw.toml"
hash = "75f83e8aa219faa8346f49cacbe5aa112428fe3f3c7c52ef017a6a4feb38d686"
metafile = true

[[files]]
file = "mods/admin-panel+.pw.toml"
hash = "6179786778ef747be74850d09a62553bfbfde2a99e94a7acc5b26f679df33b88"
metafile = true

[[files]]
file = "mods/advancedperipherals.pw.toml"
hash = "0f1e06a27168b891eee3baee61d5f727d00abc99cfe24117324fb6deb0f1ade8"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "6d852e569e918160562a52b45338b9760b69a90020da25c197cb49ee3959277c"
metafile = true

[[files]]
file = "mods/aeinfinitybooster.pw.toml"
hash = "0d7ec1712eff98e71ab90780adc6572433742fed0f039b88327025b928704f8a"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "1fb6250d6f96be86619713b54226f48b0fe4b6d95a75b2a8eee4499fed874cc3"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "63b795f7570270d26b9f85b3485c0b83d3d5c8e0cfb45bb818f210283bf4110b"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "9b4f43395feb19ba88b75369bbab89becc85fca5670537c935bbb8b508af4317"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "ee74c2613f56df0d8bebd7dcc5548bbd3db2db8b64abb23c5605d3cf6e59e3c0"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "0d0c8666e5ce90b799449973653b41437afda07770cf0b5625a018944671f067"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
hash = "7bb090b7e61c4079d0f335b63bd15a28b8cbb9bf01d92b5b758986ff0fd7db79"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "736b9723f01932e79740e648a3a67d311f3096a0593efb78a706642b0099780e"
metafile = true

[[files]]
file = "mods/chat-impressive-animation.pw.toml"
hash = "1c03815d9cb9d7a9e7c18a3b75945cb0c3e8acbe142446ff5554a89f95ea1b3c"
metafile = true

[[files]]
file = "mods/chat-plus.pw.toml"
hash = "965bd6456d1a79b754820455c17f4d935ac3ee9a6d4bb5925a8454ed362e0d30"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "a714b62b7f3f526e4311e480fa8d01ea27036c9e59d98a3fa15f4940373233ae"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "407ecd682b47f0d1ed60322f75af18dd4c71c2ceb2dd2d4e4a64f430c22bf684"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "1f67717a81f814f4c649f5046909a0e31f9fd50880aaa14f1e18d93b33eae58d"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "d95e087e12ce8c1aec15c67e6316faf4f7d676096baa900a9e993fcf9429b078"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "8185e766bd3337dba8fb9d212cba0dc974364ed2d90273c73c72430036391010"
metafile = true

[[files]]
file = "mods/create-cc-total-logistics.pw.toml"
hash = "5ae4df80f780ab19be722e7b0fbe171e0afd7268a41759807b1f3b652793c795"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "b4a4ec6c0c619d8c59905ee37b65777a3a5e8d608f928f4c151dc4ccf09df37a"
metafile = true

[[files]]
file = "mods/create-enchantable-machinery.pw.toml"
hash = "fe3b5481e0f9b3acd4cb2582c3a71873dc4b212382697a57fbefb69807d36218"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "50bd832efaaa39d98d68b99e970b2166b9297d4e10fcd59d00ff524c796a2bcf"
metafile = true

[[files]]
file = "mods/create-framed.pw.toml"
hash = "c4f0e544a067989869e28b8e7415bd0708b20d452e8261a45522bd160ce67470"
metafile = true

[[files]]
file = "mods/create-power-loader.pw.toml"
hash = "76cb8a17db5021546c4df41270603d4e7de4e10ba3895abb6ddd83f3085c00b7"
metafile = true

[[files]]
file = "mods/create-stock-bridge.pw.toml"
hash = "650af0f16cb62486cb2e6f346a8b962d2d7807b211093d09721c3e7caee08cc8"
metafile = true

[[files]]
file = "mods/create-ultimate-factory.pw.toml"
hash = "6fe67ec081f2b6ad22de743e47d3db8b8f628b9e31d4c659d16543fc5524b994"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "aad85be54105b7c2486cb99c6a9e025fd8751fd7f61e81fa089ec6ccb1a68d93"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "71157bdc340c811c99ebad1e57c8951e3b9986fb15ba3ce2a999ab62ace7006e"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "3deda5e6e3eeb64d3b66d910d9ade3e79548b35892bddd5b78d6d060824a62ee"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "67e8df6e97a59ee8cfceacee48d34daf5d1a05173c521fb589c654ac3c93c2e7"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "302b7c6584d4950342f4dd594e6fc766c29f8ca46d89917a8e9d19c77ca22ada"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7480e76010cfe686a496831c7a42a23aebf252d3b4d1dca95b4efcbd93de3af8"
metafile = true

[[files]]
file = "mods/essential.pw.toml"
hash = "cb5e15f4717d1a6705e3452be92ac8a036578e6eeff5c65ff1bef30e7977822a"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "5ae2340bf69c860238145b0ecb794b1c06e2997f45ac6d83e938f2be0e2134bb"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "2e3fde9129ef878aaa07d89bb767315b2e4a3cb03a0c65d887aae1a485f8f0f3"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "0010ae0c538d42b110546d15910c26a600ad2f18b71ed3798de0fd38334c5bc0"
metafile = true

[[files]]
file = "mods/infinite-zoom.pw.toml"
hash = "dc65f3e71f064d6bfcee96012afdcbb6215ce989aec66023ed3fa73b862b27c2"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "bf9ed3008f1e010c66bcfc724ea0454a5f7ba896ce25afe6553d86f64c070600"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "c561e0a263a7fe87da4ef38c8ff35b070bf9324869dc5d38507eef12b9c2bb3f"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "247b81af219c7d59ea5d5ad49d81e22de4a7bca20d339c1a7d68aab1022cae43"
metafile = true

[[files]]
file = "mods/loadsupport.pw.toml"
hash = "4a11cc8afb0a6966d013a4248d6826499949213c71e01c1fe69869080c1068f2"
metafile = true

[[files]]
file = "mods/mekanism-covers.pw.toml"
hash = "4bf42dcb0949701832204be2622e2061495e37cee399d77f1ef9a8b7bf1d3756"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "5ca9e4f757aa7bb6ae9bb3b2e5bcf3b4bcad644dc72f157b0ac886a349dbc4c9"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "0450fce76816ec5079723377d8f8ab518afac62ffa37be4c7fe034af63ce0ffe"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "6debe215f9a596c786ed5cabcc324a4a69def4d887ff40aefc13a9d3f40fd2e6"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "f67144a9f80e72f2fd489a9ff08b6aa90e4f5f4d2e3a641989dfcf30f9223f69"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "f251305a4c15841f7d2b95c3beee78f8f4fb1bed3221abc890d49336f5a8ca49"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "4ae6337308843ba9bfb841d842543cc35fe0ba45e769f68f808f93d6f0c8d30d"
metafile = true

[[files]]
file = "mods/neoforge-carpet.pw.toml"
hash = "230a38d2c624118912e102c5f2c620999c9a53d2fd45898ce2f23cc69b218cf5"
metafile = true

[[files]]
file = "mods/neojcm.pw.toml"
hash = "44009153ffb81b7909857b4dc19ad15c3122e25e01db257b8ea83db0e5c982bc"
metafile = true

[[files]]
file = "mods/neolu.pw.toml"
hash = "b19e8eeb0601be8de4271c80fd8db67eae3ed2a187ac1ce6dc95e42731189498"
metafile = true

[[files]]
file = "mods/neomsd.pw.toml"
hash = "db3d829d70ce77336473bca26385231f813aced6b9f5c8368d370ce64336596f"
metafile = true

[[files]]
file = "mods/neomtr.pw.toml"
hash = "263657d532fcc40a735d31cf25a109e9315b30f23b897ea78fb2b968ff2b88f1"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "df686ec8005eac1399ced2d16eacd79a133f2ab32fe9ee6967f72370185bab1d"
metafile = true

[[files]]
file = "mods/reforgedplaymod.pw.toml"
hash = "346991bb5eab485dfd6c14ef92afc9344d898baaf53ceb57d668a659406d980f"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
hash = "ce46f18bf785dae58869d1a37ad190dbd67fe6c978a12ab62ca7c6e178fd5a88"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "375c6354a5dbd2f404fa68aba66f8000a860df48aa946ae4f18e9ffb26cf212e"
metafile = true

[[files]]
file = "mods/slide-show-pro.pw.toml"
hash = "02ed9eca05875057d2c92add5445751cd8aab746ae6521c11484873dbd6f3c76"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "acfd84d21b81ef41c4d1150f31a743609366f6476547021bea6e91d87398f6b9"
metafile = true

[[files]]
file = "mods/trafficcraft.pw.toml"
hash = "efdc83622df7495fa987822875ae8c7298f6081d682121890a979a5440670683"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "f43efe97e8c619ac7ee4b39889c0132cce5b9ab9ef2d17c311b30fe2cd277f31"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "c674aa13f597acdcd672d9d121dc6dc3cabcad53829268cae2f8aa163a80fe4b"
metafile = true