name = "GGHJK Normal"
author = "GGHJK"
version = "1.0.0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a31851f62cc6264bfd1a03b655e12b11560e59f42a279f11440fb9ae5ac7bcd3"